version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    timezone: Asia/Tokyo
  open-pull-requests-limit: 99
  assignees:
  - sue445
  versioning-strategy: lockfile-only
  ignore:
  - dependency-name: rubocop
    versions:
    - 1.13.0
  - dependency-name: mini_mime
    versions:
    - 1.0.3
  - dependency-name: mimemagic
    versions:
    - 0.3.10
    - 0.3.6
  - dependency-name: msgpack
    versions:
    - 1.4.2
  - dependency-name: rspec-support
    versions:
    - 3.10.2
