inherit_gem:
  onkcop:
    - "config/rubocop.yml"
    - "config/rails.yml"
    - "config/rspec.yml"

AllCops:
  TargetRubyVersion: 2.5
  TargetRailsVersion: 5.2

Layout/AlignHash:
  EnforcedColonStyle:      table
  EnforcedHashRocketStyle: table

Rails/NotNullColumn:
  Enabled: false

RSpec/SharedExamples:
  Enabled: false
