require:
  - rubocop-performance
  - rubocop-rails

inherit_gem:
  onkcop:
    - "config/rubocop.yml"
    - "config/rails.yml"
    - "config/rspec.yml"

AllCops:
  TargetRubyVersion: 2.7
  TargetRailsVersion: 5.2

Layout/HashAlignment:
  EnforcedColonStyle:      table
  EnforcedHashRocketStyle: table

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Rails/NotNullColumn:
  Enabled: false

RSpec/SharedExamples:
  Enabled: false
