require:
  - rubocop-performance
  - rubocop-rails

inherit_gem:
  onkcop:
    - "config/rubocop.yml"
    - "config/rails.yml"
    - "config/rspec.yml"
    - "config/performance.yml"

AllCops:
  TargetRubyVersion: 3.1
  TargetRailsVersion: 6.1
  NewCops: enable

Layout/HashAlignment:
  EnforcedColonStyle:      table
  EnforcedHashRocketStyle: table

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

RSpec/MultipleMemoizedHelpers:
  Enabled: false

Rails/EnvironmentVariableAccess:
  Enabled: false

Rails/NotNullColumn:
  Enabled: false

RSpec/SharedExamples:
  Enabled: false

Style/FetchEnvVar:
  Enabled: false
