require: rubocop-performance

inherit_gem:
  onkcop:
    - "config/rubocop.yml"
    - "config/rails.yml"
    - "config/rspec.yml"

AllCops:
  TargetRubyVersion: 2.6
  TargetRailsVersion: 5.2

Layout/AlignHash:
  EnforcedColonStyle:      table
  EnforcedHashRocketStyle: table

Layout/IndentFirstArrayElement:
  EnforcedStyle: consistent

Layout/IndentFirstHashElement:
  EnforcedStyle: consistent

Rails/NotNullColumn:
  Enabled: false

RSpec/SharedExamples:
  Enabled: false
